version: '3.1'
services:
  consul:
    container_name: consul
    image: consul:1.15.4
    restart: always
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    environment:
      CONSUL_BIND_INTERFACE: eth0

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:2.24.3
    restart: always
    ports:
      - "9411:9411"

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9.0
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sec_kill
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  redis:
    container_name: redis
    image: redis:7.2.1
    restart: always
    ports:
      - "6379:6379"

secrets:
  db_password:
    file: db_password.txt
